name: "values-manager"
version: "0.1-rc1"
usage: "Manage Helm values and secrets across environments"
description: |-
  This plugin helps you manage Helm values and secrets across different environments
  while supporting multiple secret backends like AWS Secrets Manager, Azure Key Vault,
  and HashiCorp Vault.
platformCommand:
  - os: linux
    arch: amd64
    command: "$HELM_PLUGIN_DIR/bin/wrapper.sh"
  - os: darwin
    arch: amd64
    command: "$HELM_PLUGIN_DIR/bin/wrapper.sh"
  - os: darwin
    arch: arm64
    command: "$HELM_PLUGIN_DIR/bin/wrapper.sh"
  - os: windows
    arch: amd64
    command: "$HELM_PLUGIN_DIR/bin/wrapper.bat"
hooks:
  install: "scripts/install.sh"
  update: "scripts/update.sh"
