sonar.projectKey=Zipstack_helm-values-manager
sonar.organization=zipstack

# Source code settings
sonar.sources=helm_values_manager
sonar.tests=tests
sonar.python.version=3.9,3.10,3.11,3.12
sonar.coverage.exclusions=tests/**,setup.py
sonar.python.coverage.reportPaths=coverage.xml

# Quality gate settings
sonar.qualitygate.wait=true

# Analysis settings
sonar.sourceEncoding=UTF-8
