blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Discussions
    url: https://github.com/zipstack/helm-values-manager/discussions
    about: Please ask and answer questions here.
  - name: 📖 Documentation
    url: https://github.com/zipstack/helm-values-manager/tree/main/docs
    about: Check our documentation before creating an issue.
